name: Nightly retrain check
on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC nightly
jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python retrain_if_needed.py
      - name: Commit new model + logs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add models/ logs/
          git commit -m "Auto-retrain to latest version" || echo "Nothing to commit"
          git push origin main
